title: All Play Day
description: Play board games, video games, tabletop RPGs and card games at All Play Day at Fortress Sydney. Meet local game makers and discover something new.
url: "https://allplay.day"
baseurl: ""
tickets_url: "https://events.humanitix.com/sydney-games-festival-play-all-day-fortress-sydney/tickets"
mailing_list_url: "https://stats.sender.net/forms/bkR14x/view"
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-sitemap

collections:
  activities:
    output: true
    permalink: /whats-on/:name/
  faqs:
    output: false
defaults:
  - scope:
      path: ""
      type: activities
    values:
      layout: activity
web3forms:
  access_key: 5cb3e6e9-c7fd-44a3-a382-9ced386591b5
exclude:
  - Gemfile
  - Gemfile.lock
